In [6]:
import numpy as np
from matplotlib import pyplot as plt


# Generating Random Points

generate "NUMBER_OF_POINTS" points in the chosen limit and save it in "DESTINATION_FILE"

In [ ]:
DESTINATION_FILE = "10points.csv"
NUMBER_OF_POINTS = 10
X_RANGE = (0,100)
Y_RANGE = (0,100)

SEED = 42
rng = np.random.default_rng(SEED)

generated_points = rng.uniform(
    low=[X_RANGE[0], Y_RANGE[0]],
    high=[X_RANGE[1], Y_RANGE[1]],
    size=(NUMBER_OF_POINTS, 2)
)
generated_points = np.round(generated_points, 2)

np.savetxt(
    DESTINATION_FILE,
    generated_points,
    delimiter=",",
    header="x,y",
    comments="",
    fmt="%.2f"
)

# Load Data
reads the "DATA_FILE" which contains a header x, y and each row has two columns. saves the number of points into "n".

In [7]:
DATA_FILE = "10points.csv"

data = np.loadtxt("10points.csv", delimiter=",", skiprows=1)
n = data.shape[0]

In [ ]:
data

array([[77.4 , 43.89],
       [85.86, 69.74],
       [ 9.42, 97.56],
       [76.11, 78.61],
       [12.81, 45.04],
       [37.08, 92.68],
       [64.39, 82.28],
       [44.34, 22.72],
       [55.46,  6.38],
       [82.76, 63.17]])

# Distance Matrix   
dist_matrix<sub>ij</sub> holds Euclidean distance between point<sub>i</sub> and point<sub>i</sub> 

In [8]:
diff = data[:, None, :] - data[None, :, :] 
dist_matrix = np.linalg.norm(diff, axis=2) # Root of sum of square of elements in the distance vector

# Initial Population
chooses "POPULATION_SIZE" random permutations 

In [9]:
POPULATION_SIZE = 100

SEED = 42
rng = np.random.default_rng(SEED)

indices = list(range(n))

# Random permutation of indices
population = np.array([
    rng.permutation(indices) for _ in range(POPULATION_SIZE)
])

# Fitness Function
uses inverse of Total distance to make minimization into maximization problem

In [10]:
def fitness_of(c):
    Total_distance = 0
    
    for i in range(1,n):
        prev_point = c[i-1]
        next_point = c[i]

        # Distance between two consecutive points in the chromosome
        Total_distance += dist_matrix[prev_point][next_point] 

    return 1 / Total_distance
    

# Crossover
uses Ordered Crossover

In [ ]:
def crossover(parent_a, parent_b, n, rng):

    # Empty array for child
    child = np.array([-1] * n)
    
    # Keeps used indices
    used = set() 

    # Place a random part of the first parent in child
    shared_range = rng.choice(n, size=2, replace=False)
    # Put the smaller one first
    shared_range.sort()

    for i in range(shared_range[0],shared_range[1]):
        child[i] = parent_a[i]
        used.add(parent_a[i])
    
    # Fill remaining part with the second parent keeping its order
    p_ptr = 0 # Parent pointer 
    for i in range(0,n):
        # If was not filled with parent_a 
        if child[i] == -1:

            # moves forward to find the first not used point in parent_b 
            while parent_b[p_ptr] in used:
                p_ptr += 1
            
            # Places the first unused point
            child[i] = parent_b[p_ptr]
            p_ptr += 1
            # point will not be seen again so it won't be necessary to add it into used set 

    return child

In [17]:
print(population[0],population[1])
print(crossover(population[0],population[1],n,rng))

[5 6 0 7 3 2 4 9 1 8] [4 8 2 6 5 9 7 3 0 1]
[4 8 0 7 3 2 6 5 9 1]
